### ISSUE TITLE
How to change 2d text dynamicly?

### ISSUE THREAD

**Issue by JamesKnochen** [bwoodsend/vtkplotlib#19]
Im trying to display the coordinates I clicked on in the bottom left corner. 
I used the OnClick function to put the current coordinates as 2d text on the plot.
The issue is, that when I click again the next coordinates get written ontop of the others. Is there a way to delete the old coordinates?

**Comment by bwoodsend** [comment]
If you store the output of `vpl.text()`, you can write to its `.text` attribute.

```python
text = vpl.text("hello")
text.text = "good bye"
```
